### ISSUE TITLE
Cannot read property 'iso' of undefined

### ISSUE THREAD

**Issue by maxmckenzie** [nuxt-community/nuxt-i18n#80]
^ I am not handing this site a token for my github account.

i'm getting the error 

`Cannot read property 'iso' of undefined`

i'd like to know which iso you are using there is `es` v1 of the iso and `es-ES`

soooooo which is it.

**Comment by maxmckenzie** [comment]
ah i see your bot closes the ticket if i dont open it somewhere else.

**Comment by maxmckenzie** [comment]
BOOOOOOOOOOOOO!!!!! this sucks. why remove github functionality and make me use this cmty thing.

BOOOOOOOOOOOOOOOO

**Comment by maxmckenzie** [comment]
even when you use the correct ISO code there is still the error.

**Comment by paulgv** [comment]
Hi @maxmckenzie 
What does your config look lilke?

**Comment by maxmckenzie** [comment]
Hey @paulgv thanks so much for the reply, unfortunately, I'm working on a time-sensitive project. So I've now gone with just using vue and rolling my own boilerplate. As such i've removed the config and i didnt commit a version of it so its not in my git history.

If i get some time spare i shall try to replicate the issue.

**Comment by mahnuh** [comment]
@paulgv here you can find a project with this error: https://github.com/mahnuh/nuxt-test

**Comment by paulgv** [comment]
Thanks @mahnuh !
There were some checks missing in the SEO plugin, the issue should be fixed in v3.2.2 :smiley:

**Comment by mahnuh** [comment]
Thanks @paulgv , you just made my day - again! 😃

**Comment by shrpne** [comment]
@paulgv 
I have the same issue, but only on 404 page, 
Nuxt-i18n version is 4.0.0, my config:
```
    modules: [
        ['nuxt-i18n', {
            locales: [
                {
                    code: 'ru',
                    iso: 'ru',
                },
                {
                    code: 'en',
                    iso: 'en',
                },
            ],
            strategy: 'prefix',
            rootRedirect: 'ru/1',
            vueI18n: {
                fallbackLocale: 'ru',
                messages: {
                    ru: {
                        welcome: 'Welcome'
                    },
                    en: {
                        welcome: 'Bienvenue'
                    },
                }
            },
        }]
    ]
```

**Comment by begueradj** [comment]
I am facing the same issue with the current Nuxt version (2.1.0)

**Comment by acidjazz** [comment]
@gnuletik @paulgv I'm still getting this error with nuxtjs v2.4.3 and nuxt-i18n v5.8.4

Instead of redirecting or giving a proper 404 when i hit any older page (aka `/careers` which is now `/en/careers`) I get "Cannot read property 'iso' of undefined"


![image](https://user-images.githubusercontent.com/967369/53376810-3bb80680-3925-11e9-8416-ebc7fd8897f4.png)




```js
    ['nuxt-i18n', {
      locales: [
        {
          code: 'en',
          iso: 'en-US',
        },
        {
          code: 'jp',
          iso: 'ja',
        },
      ],
      deafultLocale: 'en',
      rootRedirect: 'en',
      vueI18n: { fallbackLocale: 'en', },
    }]```

**Comment by rchl** [comment]
I've looked a bit at the code.

With default strategy (`prefix_except_default`), with two pages: `index.vue` and `about.vue`, these routes are generated:

```
    routes: [{
      path: "/en/about",
      component: _33ee994b,
      name: "about___en"
    }, {
      path: "/jp/about",
      component: _33ee994b,
      name: "about___jp"
    }, {
      path: "/en/",
      component: _53a67410,
      name: "index___en"
    }, {
      path: "/jp/",
      component: _53a67410,
      name: "index___jp"
    }],
```

As there is no `/about` route being generated, the whole redirection logic fails because it can only redirect *from existing routes* due to needing route's *name* to properly resolve current route and route to redirect to.

The behavior is slightly different whether it's first redirect in the app or subsequent. On first it will redirect from unknown route to `index`. After that, when cookie is already set, it will just fail with error above (unless `alwaysRedirect: true` I guess).

It's IMO also buggy that on first redirect it will redirect to index. It should probably just trigger 404 if it can't figure out which route to redirect to.

One way to fix it would potentially be to add code to resolve route by path. If user visits non-existing route like `/about`, we would add defaultLocale prefix and try to resolve by path. But then when user visits `/xx/about`, maybe we should strip the 'xx' prefix and then add default locale. Not sure how smart it would need to be.

**Comment by rchl** [comment]
Created PR #233 that will fix the crash but won't fix/change redirection logic.
